version: '2.1'

services:  
  tomcatwar:
     extra_hosts:
        - "local:10.1.2.232"
     image: sopheamak/springboot_docker_mysql
     ports:
         - 8080:8080
     environment:
            - DATABASE_HOST=local
            - DATABASE_NAME=demo
            - DATABASE_PORT=3306
            - DATABASE_USER=root
            - DATABASE_PASSWORD=root
 
