version: '2.1'

services:
  mysql:
        image: mysql:5.7
        environment:
           - MYSQL_ROOT_PASSWORD=root
           - MYSQL_DATABASE=demo
           - MYSQL_USER=demo_user
           - MYSQL_PASSWORD=demo_pass
        ports:
            - 3306:3306
            
  tomcatwar:
     image: sopheamak/springboot_docker_mysql
     links:
      - mysql:mysql
     ports:
         - 8080:8080
     environment:
            - DATABASE_HOST=mysql
            - DATABASE_USER=demo_user
            - DATABASE_PASSWORD=demo_pass
            - DATABASE_NAME=demo
            - DATABASE_PORT=3306
 
