version: '2'

services:
  mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: demo
            MYSQL_USER: demo_user
            MYSQL_PASSWORD: demo_pass
        ports:
            - "3306:3306"
            
  app1:
     image: "nexus101-3.dminc-gtc.com:50000/test-backend:1.3-SNAPSHOT"
     depends_on:
      - mysql
     environment:
              DATABASE_HOST: mysql
              DATABASE_USER: demo_user
              DATABASE_PASSWORD: demo_pass
              DATABASE_NAME: demo
              DATABASE_PORT: 3306
 
  app2:
     image: "nexus101-3.dminc-gtc.com:50000/test-backend:1.3-SNAPSHOT"
     depends_on:
      - mysql
     environment:
              DATABASE_HOST: mysql
              DATABASE_USER: demo_user
              DATABASE_PASSWORD: demo_pass
              DATABASE_NAME: demo
              DATABASE_PORT: 3306

  app3:
     image: "nexus101-3.dminc-gtc.com:50000/test-backend:1.3-SNAPSHOT"
     depends_on:
      - mysql
     environment:
              DATABASE_HOST: mysql
              DATABASE_USER: demo_user
              DATABASE_PASSWORD: demo_pass
              DATABASE_NAME: demo
              DATABASE_PORT: 3306
 
  portal:
    image: nginx
    depends_on:
      - mysql
    ports:
        - "8080:80"
    volumes:
        - /data/workspace_android/git/spring-boot-docker-mysql/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - app1:app1
        - app2:app2
        - app3:app3